version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "markdownquiz"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-868icu6dmbox"
s3_prefix = "markdownquiz"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
